# Site settings
title: Zeeik’s Blogs
SEOTitle: Zeeik’s Blogs | 77
header-img: img/post-bg-desk.jpg
email: wuzichi@qq.com
description: "Welcome to my blogs"
keyword: "Zeeik’s Blogs"
url: "https://zeeki.top"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/wuzichi/wuzichi.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Zeeki Woo"
sidebar-avatar: /img/me.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     暂无
#zhihu_username:     暂无
github_username: wuzichi
#facebook_username:  暂无
#jianshu_username:   暂无
twitter_username: ZeekiWoo



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
#redcarpet:
#    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 578ee553737c09f6b5bb #生成的clientID
  clientSecret: c6e4d555d59b9f7b86cb133b6b8331ba0235df18 #生成的clientSecret
  repo: wuzichi.github.io    #仓库名称
  owner: wuzichi #github用户名
  admin: 
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain:                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "Github",
        href: "https://github.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "GDMU",
        href: "http://www.gdmu.edu.cn"
    },
]

navbar-links:
  
  搜索: "search"